# -*- coding: utf-8 -*-
"""
Created on Mon Jan 22 11:42:04 2024

@author: Alvise Ferrari
PRISMA L1C to GeoTiff converter

"""


import os
import sys
import argparse
import numpy as np
import h5py
from osgeo import gdal


def prisma_read(filename):
    """

    """
    # Open the HDF5 file
    with h5py.File(filename, 'r') as f:
        # Read the VNIR and SWIR spectral data
        vnir_cube_DN = f['HDFEOS/SWATHS/PRS_L1_HCO/Data Fields/VNIR_Cube'][:]
        swir_cube_DN = f['HDFEOS/SWATHS/PRS_L1_HCO/Data Fields/SWIR_Cube'][:]
    
        # Read central wavelengths and FWHM for VNIR and SWIR bands
        cw_vnir = f['KDP_AUX/Cw_Vnir_Matrix'][:]
        fwhm_vnir = f['KDP_AUX/Fwhm_Vnir_Matrix'][:]
        cw_swir = f['KDP_AUX/Cw_Swir_Matrix'][:]
        fwhm_swir = f['KDP_AUX/Fwhm_Swir_Matrix'][:]
    
        # Read scale factor and offset to transform DN to radiance physical value
        offset_swir = f.attrs['Offset_Swir']
        scaleFactor_swir = f.attrs['ScaleFactor_Swir']
        offset_vnir = f.attrs['Offset_Vnir']
        scaleFactor_vnir = f.attrs['ScaleFactor_Vnir']
    
    # Convert DN to radiance for VNIR and SWIR data #[W/(str*um*m^2)]
    swir_cube_rads = (swir_cube_DN / scaleFactor_swir) - offset_swir
    vnir_cube_rads = (vnir_cube_DN / scaleFactor_vnir) - offset_vnir
    
    #Convert PRISMA radiance from [W/(str*um*m^2)] to [μW*cm-2*nm-1*sr-1] in order to meet original AVIRIS radiance unit.
    swir_cube_rads = swir_cube_rads * 0.1
    vnir_cube_rads = vnir_cube_rads * 0.1
    
    # Convert from BIL to BIP format ( BIL = M-3-N ; BIP = 3-M-N ; BSQ = M-N-3 )
    vnir_cube_bip = np.transpose(vnir_cube_rads, (0, 2, 1))
    swir_cube_bip = np.transpose(swir_cube_rads, (0, 2, 1))

    return vnir_cube_bip, swir_cube_bip




def save_to_tiff(data_cube, output_file):
    """
    Saves a data cube as a non-georeferenced TIFF file with metadata.
    
    Parameters:
    data_cube (numpy array): The data cube to save.
    output_file (str): The path to the output file.
    description (str): The description to be added as metadata.
    """
    # Ensure the data is in float32 format
    data_cube_float32 = data_cube.astype(np.float32)
    
    # Determine the number of bands, and the size of the image
    width, height, bands = data_cube.shape
    
    # Set the driver (for TIFF)
    driver = gdal.GetDriverByName('GTiff')
    
    # Create a new dataset
    dataset = driver.Create(output_file, data_cube.shape[0], data_cube.shape[1], data_cube.shape[2], gdal.GDT_Float32)
    
    # Metadata statement
    description = ("This product has been generated by your Alvise Ferrari fo School of Aerospace Engineering (La Sapienza). "
                          "The dissemination of this product is closely linked to the agreements established. "
                          "The authors of the code by which the product was generated cannot be held responsible "
                          "for any improper use or dissemination of this product")
    
    # Set specific metadata
    dataset.SetMetadataItem('DESCRIPTION', description)
    
    # Write the data for each band
    for i in range(bands):
        dataset.GetRasterBand(i + 1).WriteArray(data_cube_float32[:, :, i])
    
    # Save and close the dataset
    dataset.FlushCache()
    dataset = None



def main(filename):
    # Extract the base path and the file name without the extension
    base_path, full_filename = os.path.split(filename)
    filename_without_extension = os.path.splitext(full_filename)[0]
    
    # Define output filenames
    vnir_output_file = os.path.join(base_path, f"{filename_without_extension}_vnir.tif")
    swir_output_file = os.path.join(base_path, f"{filename_without_extension}_swir.tif")
    
    # Extract VNIR/SWIR full PRISMA Datacube, removing redundant and zeroed bands, and correspondant CWs and FWHMs
    vnir_cube_rads, swir_cube_rads = prisma_read(filename)
    
    # Save GeoTIFF
    save_to_tiff(vnir_cube_rads, vnir_output_file)
    save_to_tiff(swir_cube_rads, swir_output_file)
    


# INPUT

#Read PRISMA image
#filename = r"G:\CLEAR_UP\CH4_detection\img_PRISMA\Turkmenistan\PRS_L1_STD_OFFL_20200622072439_20200622072443_0001.he5" #Turkmenistan
#filename = r"G:\CLEAR_UP\CH4_detection\img_PRISMA\Shanxi\Shanxi_20210206031837\PRS_L1_STD_OFFL_20210206031837_20210206031842_0001.he5" #Shanxi
#filename = "G:/CLEAR_UP/CH4_detection/img_PRISMA/Immagini_Pirana_Landfill/L1/PRS_L1_STD_OFFL_20211103055234_20211103055239_0001.he5" #Pirana Landfill
#filename = r"G:\CLEAR_UP\CH4_detection\img_PRISMA\Algeria\Hassi_Messaoud\PRS_L1_STD_OFFL_20200830103014_20200830103018_0001.he5" #Hassi Messaoud
#filename = r"G:\CLEAR_UP\CH4_detection\img_PRISMA\Buenos_Aires\BuenosAires_20220111\PRS_L1_STD_OFFL_20220111140337_20220111140342_0001.he5" #Buenos Aires
#filename = r"G:\CLEAR_UP\CH4_detection\img_PRISMA\Dehli\Dehli_20230605\PRS_L1_STD_OFFL_20230605053706_20230605053711_0001.he5" #Dehli


if __name__ == "__main__":
    # parser = argparse.ArgumentParser(description="Run hyperspectral image processing")
    # parser.add_argument("filename", type=str, help="Path to the input file (PRISMA image)")

    # args = parser.parse_args()

    # try:
    #     main(args.filename) 
    # except Exception as e:
    #     print(f"An error occurred: {e}", file=sys.stderr)
        # Use this line instead for testing
    filename = filename
    
    try:
        main(filename)
    except Exception as e:
        print(f"An error occurred: {e}", file=sys.stderr)